### ISSUE TITLE
Zoom rectangular cursor does not follow the mouse 

### ISSUE THREAD

**Issue by yoichi-kazama** [matplotlib/jupyter-matplotlib#119]
![Clipboard01](https://user-images.githubusercontent.com/44988698/60699080-e61fe600-9f24-11e9-9f34-2d711e6798db.png)

Firefox 67.0.4, Windows 8.1
```
jupyterlab                1.0.1                    py37_0    conda-forge
jupyterlab_server         1.0.0                      py_0
matplotlib                3.1.1                    py37_0    conda-forge
matplotlib-base           3.1.1            py37h2852a4a_0    conda-forge
ipympl                    0.3.2                      py_0    conda-forge
ipywidgets                7.5.0                      py_0    conda-forge
```

**Comment by martinRenou** [comment]
That is bad, I'll look into it

**Comment by martinRenou** [comment]
@yoichi-kazama This should be fixed in the last release `0.3.3`

**Comment by tacaswell** [comment]
Ah, great I also hit this last night.  The factor of 2 for hidpi screens is surprisingly hard to keep straight...

**Comment by yoichi-kazama** [comment]
Hi @martinRenou, thank you for your quick response. I confirmed it's fixed.
