### ISSUE TITLE
No plot, just `FigureCanvasNbAgg()` in JupyterLab

### ISSUE THREAD

**Issue by dmopalmer** [matplotlib/jupyter-matplotlib#128]
In Jupyter**Lab**, when I try to make an interactive (zoom/pan/etc) plot with 
```
%matplotlib widget
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```

There is no plot.  The output is just 
```
FigureCanvasNbAgg()
[1]: [<matplotlib.lines.Line2D at 0x12b2f9f60>]
```

The same code works perfectly in Jupyter **Notebook**.

Looking at `matplotlib.rcParams['backend']` gives `'module://ipympl.backend_nbagg'` in both environments.

`%matplotlib ipympl` gives the same output.

`%matplotlib inline` gives a non-interactive plot (as expected).

`%matplotlib inline` gives
```
Javascript Error: Can't find variable: IPython [<matplotlib.lines.Line2D at 0x1261cab70>]
```

This is under an Anaconda install of python 3.6.8 on macOS.

1. Should this work (_i.e._, is jupyter-matplotlib only for **Notebook** or is it for **Lab** as well)?
2. Is there experience where it has worked with Anaconda+macOS+Lab?
3. Is there some other `%matplotlib <magic>` or `backend` setting that works better?
4. Should this be filed as an _issue_ on jupyterlab/jupyterlab instead?

**Comment by thomasaarholt** [comment]
Did you follow the jupyter lab instructions in the readme on the github?
```python
# Instructions from July 2019
conda install -c conda-forge ipympl

# If using the Notebook
conda install -c conda-forge widgetsnbextension

# If using JupyterLab
conda install nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
```

**Comment by dmopalmer** [comment]
That is probably the reason.  I know that I ran all those commands, but I may not have run them all in the same conda environment.

Creating a fresh environment and kernel
```
conda create -y -n jlabtest -c conda-forge python=3.7 jupyterlab ipympl nodejs widgetsnbextension ipython ipykernel matplotlib
conda activate jlabtest
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
python -m ipykernel install --user --name jlabtest --display-name="jlabtest matplotlib"
jupyter-lab
```

I get interactive plots in jupyter-lab.

Trying to run the equivalent commands on a pre-existing conda environment leaves me in a state where running in that environment's kernel I get:
```
Error displaying widget: model not found
```
instead of the plot.

I will burn down and re-build that environment and make sure it works, but I think you can close this as an RTFM error.

**Comment by thomasaarholt** [comment]
You (or an admin) need to close it yourself :)

**Comment by dmopalmer** [comment]
This was a failure to properly read and apply instructions.
