### ISSUE TITLE
Plot not displayed, instead text output  "Canvas(toolbar=Toolbar..."

### ISSUE THREAD

**Issue by Nestak2** [matplotlib/jupyter-matplotlib#133]
I run the minimal code in the screenshot on Jupyter Lab and get instead of the plot the strange text output at the bottom of the screenshot:
![Screenshot 2019-08-03 at 14 26 48](https://user-images.githubusercontent.com/16193553/62412469-c8fd3680-b5fa-11e9-91ce-495b1e18abf5.png)

Jupyter Lab version: 0.33.12
Jupyter Notebook version: 5.7.2

I have installed everything as [required here](https://github.com/matplotlib/jupyter-matplotlib). Other users are having the same problem as reported [here](https://stackoverflow.com/questions/57317106/widget-and-graph-dont-show-up-in-jupyter-lab-they-show-up-as-text) and more extensively [here](https://aur.archlinux.org/pkgbase/python-ipympl/?O=0&PP=10). It seems to be a due to the new version of Jupyter Lab or ipympl. If I use Jupyter Notebook instead of Jupyter Lab the figure is not displayed either. Anyways, `%matplotlib inline` works both for Notebook and Lab for the static display. What should I do to display the plot interactively. Can I go to a previous version of Jupyter Lab and make it work again?

**Comment by jasongrout** [comment]
ipympl only supports jlab 1.0 and widgets 7.5 or above (https://github.com/matplotlib/jupyter-matplotlib/blob/master/js/package.json#L30). If that line is changed to `^1 || ^2`, it will likely work with older jlab and widgets versions. You'll still need to install the appropriate version of the widgets jlab extension: https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#version-compatibility

CC @martinRenou

**Comment by Nestak2** [comment]
@jasongrout Thanks a lot, indeed upgarding to jlab 1.02 solved my problem, now the plots are being displayed and they are interactive
