### ISSUE TITLE
Change/disable header

### ISSUE THREAD

**Issue by maartenbreddels** [matplotlib/jupyter-matplotlib#134]
The Figure ID is shown in the header (Figure 14):
![image](https://user-images.githubusercontent.com/1765949/63501218-8e850c00-c4cb-11e9-82f7-0f91d576ed9c.png)

Is there an option to change or remove/hide it?

**Comment by martinRenou** [comment]
No, but that could be a nice addition

**Comment by freethebee** [comment]
I did a quick and dirty fix, but still need to check if I didn't miss anything, write tests and see how to do a proper pull request.

```
--- a/ipympl/backend_nbagg.py
+++ b/ipympl/backend_nbagg.py
@@ -149,6 +149,9 @@ class Canvas(DOMWidget, FigureCanvasWebAggCore):
     toolbar = Instance(Toolbar, allow_none=True).tag(sync=True, **widget_serialization)
     toolbar_visible = Bool(True).tag(sync=True)
     toolbar_position = Enum(['top', 'bottom', 'left', 'right'], default_value='left').tag(sync=True)
+
+    header_visible = Bool(True).tag(sync=True)
+
     _closed = Bool(True)

     # Must declare the superclass private members.
diff --git a/js/src/mpl_widget.js b/js/src/mpl_widget.js
index c8c8585..ee547cd 100644
--- a/js/src/mpl_widget.js
+++ b/js/src/mpl_widget.js
@@ -16,6 +16,7 @@ var MPLCanvasModel = widgets.DOMWidgetModel.extend({
             _view_module: 'jupyter-matplotlib',
             _model_module_version: '^'+ version,
             _view_module_version: '^' + version,
+            header_visible: true,
             toolbar: null,
             toolbar_visible: true,
             toolbar_position: 'horizontal'
@@ -64,6 +65,7 @@ var MPLCanvasView = widgets.DOMWidgetView.extend({

     model_events: function() {
         this.model.on('msg:custom', this.on_comm_message.bind(this));
+        this.model.on('change:header_visible', this.update_header_visible.bind(this));
         this.model.on('change:toolbar_visible', this.update_toolbar_visible.bind(this));
         this.model.on('change:toolbar_position', this.update_toolbar_position.bind(this));
     },
@@ -78,6 +80,11 @@ var MPLCanvasView = widgets.DOMWidgetView.extend({
         this.send_message('initialized');
     },

+    update_header_visible: function() {
+        this.header.style.display = this.model.get('header_visible') ? '': 'none';
+        this.request_resize();
+    },
+
```

**Comment by thomasaarholt** [comment]
@freethebee That's great! If you push the changes to a new branch on your fork, github will show a button telling you how to make a Pull Request. That'll make it easier for us to see which changes you've made. I think you can go ahead with that even before making tests.

**Comment by freethebee** [comment]
I made the pull request, and will give a bit more info. My code was borrowed from the toolbar_visible option on the figure canvas. 

When using it, I run into libpng problems discussed in issue #127. 

Here are three cases, I checked.
Removing the header in before rendering the figure results in RuntimeError: libpng signaled error.
```
fig, ax = plt.subplots()
fig.canvas.header_visible = False
ax.plot([1,2,3], [4,5,3])
```

Making and rendering the figure in once cell and then hiding header from another, works.
```
In [1]:  fig, ax = plt.subplots()
 ax.plot([1,2,3], [4,5,3])
In [2]: fig.canvas.header_visible = False
```

Making rendering, and hiding both the toolbar and the header works.
```
fig, ax = plt.subplots()
fig.canvas.toolbar_visible = False
fig.canvas.header_visible = False
ax.plot([1,2,3], [4,5,3])
```

**Comment by martinRenou** [comment]
> Is there an option to change or remove/hide it?

Just for the record, it is possible to change it doing `fig.set_label('Test')` and to "kindof" remove it doing `fig.set_label(' ')`.

But now that #135 is merged it will be possible to properly hide it.

**Comment by gsaurabhr** [comment]
This is great; quick question to those familiar: is there a good way to set the flag as a notebook-wide default? It would be better than setting the flag for each figure every time something is plotted.

**Comment by martinRenou** [comment]
Unfortunately no... It is a widget specific flag, it is not part of the Matplotlib official API. So it is not possible to pass it to `plt.figure()` nor put it in the config.

**Comment by thomasaarholt** [comment]
I guess we could create a ipympl.rcParams equivalent?

**Comment by martinRenou** [comment]
Indeed that could be a good idea. I'd suggest we open a specific issue for that in order to keep track on this discussion.

**Comment by endolith** [comment]
Is there any way to keep the Save button while hiding the zoom and pan buttons of fig.canvas.toolbar_visible?
