### ISSUE TITLE
compatibility with ipywidgets-7.0.0 and later ?

### ISSUE THREAD

**Issue by stonebig** [matplotlib/jupyter-matplotlib#15]
With latest ipywidgets-7.0.0b6 , the example https://github.com/matplotlib/jupyter-matplotlib/blob/master/examples/ipympl.ipynb runs srtangely on classic notebook (not really usable).

**Comment by stonebig** [comment]
news ? hope ?

**Comment by SylvainCorlay** [comment]
@stonebig I am a bit swamped with work right now, but I *really* want to give ipympl the attention it deserves. We can certainly fund an intern (in Paris) to work on that and related subjects (e.g. gallery for widgets, binary messages for diffs of pngs in ipympl, etc).

If you can think of a good candidate, send it our way.

**Comment by stonebig** [comment]
Bloomberg is visiting some IT schools in France for recruitment. they may take this as an opportunity to pre-test future recruits.

**Comment by SylvainCorlay** [comment]
Well this would be with @QuantStack.
