### ISSUE TITLE
Jupyter notebook dark mode matplotlib message text not visible

### ISSUE THREAD

**Issue by andrewmkiss** [matplotlib/jupyter-matplotlib#156]
When changing to dark mode the message for the cursor location in the lower-right corner is not visible. By changing the color of the element in the CSS code, it is visible. Is there a way to automate this?

The span that needs to have this applied is: `.mpl-message`

@tacaswell Also saw this issue

**Comment by martinRenou** [comment]
There is, using JupyterLab CSS variables. I thought this was added already.

**Comment by tacaswell** [comment]
We don't see it on a newer version of ipympl (I forget the system we were working on is pinned on a very old version for .... reasons...).

**Comment by jasongrout** [comment]
> We don't see it on a newer version of ipympl

don't see the text, or don't see the issue? i.e., are you saying this is solved in recent versions, and the issue can be closed?

**Comment by tacaswell** [comment]
Sorry, I mean we don't see the problem (that is we can see the text) with newer versions of ipympl and jlab. 

This is a duplicate of https://github.com/matplotlib/jupyter-matplotlib/issues/77 which is fixed on master.

Sorry for the noise on our side (I was sitting next to @andrewmkiss and asked him to open this issue).
