### ISSUE TITLE
ipympl version 0.4.0 available but not released?

### ISSUE THREAD

**Issue by davidfokkema** [matplotlib/jupyter-matplotlib#157]
On PyPI and conda-forge, ipympl version 0.4.0 is available. However, there is no 0.4.0 release in this GitHub repository. Did a developer release it from a local system without pushing the latest commits to GitHub?

**Comment by SylvainCorlay** [comment]
Indeed, I failed to push the tag. I seems I had a network error and did not read the message. Closing!
