### ISSUE TITLE
0.4.1 on conda-forge feedstock?

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/jupyter-matplotlib#168]
I'm not aware of the exact actions needed for this, but it would be nice if we can put 0.4.1 on condaforge.

Additionally, I notice that 0.4 and 0.4.1 are not recognised as "latest version" on github / [releases](https://github.com/matplotlib/jupyter-matplotlib/releases):
![image](https://user-images.githubusercontent.com/2721423/72680542-40485900-3abb-11ea-96a7-1d2a4f438d56.png)

**Comment by SylvainCorlay** [comment]
0.4.1 is now on conda forge.

Closing this.

We did not use the GH releases for other tags than 0.3.3. Will fix this separately.
