### ISSUE TITLE
Placing BQPlot in IPYVuetify template

### ISSUE THREAD

**Issue by jy247** [matplotlib/jupyter-matplotlib#169]
Hi, 

I am creating a dashboard using Voila, BQplot and IPYVuetify.   At the moment I am just creating the figure(s) so they are above the controls (which are defined in a template), but it would be great if they could be embedded in the HTML template definition somehow.

Is this currently possible?  Are there any examples you could share?

Many thanks again

Jack

**Comment by martinRenou** [comment]
Sorry but this has nothing to do with jupyter-matplotlib. Please ask your question on a relevant repository like https://github.com/mariobuikhuizen/ipyvuetify.
