### ISSUE TITLE
'Error displaying widget: model not found' in JupyterLab 2.0.0

### ISSUE THREAD

**Issue by pythonic2020** [matplotlib/jupyter-matplotlib#193]
Hi,

I just installed JLab 2.0.0, and ipympl 0.5.2 will not display plots with the referenced error.  I re-installed the labextensions. When I first started JLab, I got an error regarding the re-build of ipympl.  Did ipympl build correctly with the new Jlab version?  How can I re-build ipympl for JLab?  

I get these JS errors:

> Could not instantiate widget manager-base.js:258:47
>     _make_model manager-base.js:258
>     l manager-base.js:38
>     s manager-base.js:23
>     s manager-base.js:10

> Error: "Module jupyter-matplotlib, semver range ^0.7.1 is not registered as a widget module"

ipympl is working fine in a Notebook.  I'm using Firefox, and I have refreshed cache.

Thanks in advance.

Setup:

```
>conda -V
conda 4.8.2
```

```
>conda list "ipympl|python|jupyter|notebook|conda|widgetsnbextension|nodejs"
# packages in environment at C:\Users\me\Anaconda3\envs\forge:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.12                   py37_0
anaconda-project          0.8.4                      py_0
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.4.2                      py_1
ipympl                    0.5.2                      py_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            6.0.0                      py_0    conda-forge
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py37_0    conda-forge
jupyterlab                2.0.0                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0
jupyterthemes             0.20.0                     py_1    conda-forge
msgpack-python            1.0.0            py37he980bc4_0    conda-forge
msys2-conda-epoch         20160418                      1
nodejs                    13.9.0                        0    conda-forge
notebook                  6.0.3                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
python-libarchive-c       2.9                      py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0
```
```
>jupyter labextension list
JupyterLab v2.0.0
Known labextensions:
   app dir: C:\Users\me\Anaconda3\envs\forge\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v2.0.0-rc.3 enabled  ok
        jupyter-matplotlib v0.7.1 enabled  ok
```

**Comment by martinRenou** [comment]
Thanks a lot for opening an issue! I don't think we tried ipympl with the new JupyterLab version. I will look into it.

**Comment by martinRenou** [comment]
In the meantime, using JupyterLab 1.x works, so if you don't have a strong reason to use JupyterLab 2.x I could suggest to downgrade your JupyterLab.

**Comment by SylvainCorlay** [comment]
@pythonic2020 jupyterlab 2.0 was released just yesterday. We need to update a number of extensions to support this new version.

Please bear with us. This should take a week or so.

**Comment by pythonic2020** [comment]
Thank you both for responding, and for all your expert work on ipympl!  Bokeh also needs to update their JupyterLab extension.  I'll downgrade my JL now.  Keep up the great work!!!!!!!!  All the best, Pythonic2020.
