### ISSUE TITLE
Update readme install instructions

### ISSUE THREAD

**Issue by soamaven** [matplotlib/jupyter-matplotlib#20]
For the conda install `conda install ipympl -c conda-forge`, I still need to run `jupyter nbextension enable --py --sys-prefix ipympl` afterward to activate the extension, but this isn't clear in the readme, or the conda package is intended to handle this but doesn't properly.

**Comment by stonebig** [comment]
a fresh release on pypi would also be appreciated

**Comment by blink1073** [comment]
Hi @soamaven, the extension should be auto-enabled when installing from `conda-forge` (it runs the enable command after installing).

I just released 0.0.6 on PyPI, with a conda-forge release pending.

**Comment by stonebig** [comment]
ipympl-0.0.8 is on pypi, no. thanks a lot for the effort.
