### ISSUE TITLE
Feature Suggestion: Splitmap Control in context of image processing

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/jupyter-matplotlib#200]
Hi, 
I am really amazed by the [SplitMap Control function](https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html)  from the ipyleaflet package.

I think that would have also great use in other situations, for example in image processing to have a fast option to see the "previous/after" change.
To get concrete, it could look like this:
```py
from skimage import data
from skimage.util import random_noise
import matplotlib.pyplot as plt
import numpy as np

img = data.chelsea()
noisy_img = random_noise(img, var=0.02)

fig1= plt.figure()
plt.imshow(img)
plt.axis('off')
fig2= plt.figure()
plt.imshow(noisy_img)
plt.axis('off')

#new part (does not exist yet):
from ipywidgets import SplitMapControl
control = SplitMapControl(left_layer=fig1, right_layer=fig2)
m.add_control(control)
m
```

![neue](https://user-images.githubusercontent.com/44469195/71660160-73b08700-2d4a-11ea-9838-7dedb2a40f1f.png)

I ask people from matplotlib https://github.com/matplotlib/matplotlib/issues/16064 , and they think this feature could be  "a reasonable downstream package rather than a base feature".
My idea where this feature could fit in would be [ipywidgets](https://github.com/jupyter-widgets/ipywidgets).
Also I ask at https://github.com/jupyter-widgets/ipyleaflet/issues/453, and the suggestion there was to directly use this feature directly in ipyleaflet, but I think this can be done nicer.

I really would like to do something like this, but I don't know where to start..
Do you have any ideas/advices or even motivation to program along?

**Comment by martinRenou** [comment]
Hey again!
I guess a custom widget might be a good idea. I can provide help for that.

**Comment by kolibril13** [comment]
Hi @martinRenou ,
thanks a lot, that is really nice of you!
I just followed the instructions from https://github.com/jupyter-widgets/widget-cookiecutter and made a github repo called jupyter splitview.
https://github.com/kolibril13/jupyter-splitview
A notebook with the cat to test is here:
https://github.com/kolibril13/jupyter-splitview/blob/master/test/test01.ipynb

**Comment by martinRenou** [comment]
Nice! I suggest we continue this discussion in your repo ;)
