### ISSUE TITLE
compatibility with seaborn and/or Notebook-5.2.0 and/or %matplotlib directive ?

### ISSUE THREAD

**Issue by stonebig** [matplotlib/jupyter-matplotlib#23]
On  a  Notebook-5.2.0, If I do this:
````
import ipympl
import matplotlib.pyplot as plt2

plt2.plot([0, 1, 2, 2])
plt2.show()
````

then next cell, I have to put a %matpollib inline to get my seaborn image, otherwise nothing is displayed:

````
%matplotlib inline
# Seaborn
# for more examples, see http://stanford.edu/~mwaskom/software/seaborn/examples/index.html
import seaborn as sns
sns.set()
df = sns.load_dataset("iris")
sns.pairplot(df, hue="species", size=1.5)
````

is it normal ?

**Comment by stonebig** [comment]
same if I stay on plt instead of plt2:
![ipympl](https://user-images.githubusercontent.com/4312421/32144377-1a88ebe0-bcb8-11e7-9bd7-69d31e042151.PNG)

**Comment by stonebig** [comment]
if I do %matplotlib inline in first cell, I get some bad words:
![ipympl2](https://user-images.githubusercontent.com/4312421/32144406-8bf8f9e6-bcb8-11e7-875b-e8ac96151367.PNG)

**Comment by stonebig** [comment]
ah, on jupyterlab side:

````
jupyter nbextension enable --py --sys-prefix ipympl
...
...
...
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/matplotlib-jupyter
npm ERR! 404
npm ERR! 404  'matplotlib-jupyter' is not in the npm registry.
````

**Comment by SylvainCorlay** [comment]
@stonebig no need for `%matplotlib inline`. Just an extra call to `plt.show()` after your seaborn command does the job.

**Comment by blink1073** [comment]
I updated the README, it should be `jupyter labextension install jupyter-matplotlib`.

**Comment by SylvainCorlay** [comment]
Closing since both questions were resolved.
