### ISSUE TITLE
Clarification on import ipympl vs IPython magics

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/jupyter-matplotlib#39]
I find myself a bit confused on whether I "want" to use `import ipympl` or `%matplotlib ipympl` at the beginning of a notebook in lab.

Could someone clarify the difference? I've noticed that the import statement requires calling `plt.show()` to show figures, whilst the magic automatically shows them. If I later call `%matplotlib inline` for static plotting, I lose the ipympl functionality, and even calling `%matplotlib ipympl` will not bring it back.

Is calling `%matplotlib ipympl` just a kind of "legacy" after `%matplotlib notebook`?

As a bonus question (extra points! 😛  ) how does #35's `%matplotlib widget` play into all this?

**Comment by blink1073** [comment]
I think the difference is whether you want to embed a `matplotlib` widget into a larger widget layout or have manual control over the widget display.  If not, you can use `%matplotlib ipympl` or `%matplotlib widget` (which is an alias to the former) for the "magic" behavior.

**Comment by thomasaarholt** [comment]
Thanks for the reply!
