### ISSUE TITLE
Resize handle feature

### ISSUE THREAD

**Issue by leolchat** [matplotlib/jupyter-matplotlib#44]
I am really missing the ability to resize the plot with the mouse like in the picture bellow with the grey bottom right corner arrow.

![](http://i.imgur.com/nqJo2Jn.png)

**Comment by thomasaarholt** [comment]
Seconded, this would be very nice to have, like in the notebook backend.

**Comment by wookayin** [comment]
This feature is a must-have. It's quite ugly, but one can write a dirty-and-quick custom widget for resizing the figure, that would give a small slidebar widget:

```python
# fig : a Figure instance

def resize_fig(size):
  fig.canvas.layout.width = '%dpx' % size
  fig.canvas.layout.height = '%dpx' % size
  fig.tight_layout()

import ipywidgets as widgets
widgets.interact(resize_fig, size=(0, 1000, 100))
```

**Comment by BrenBarn** [comment]
I also agree this is an essential feature.  The loss of this feature between notebook and widget backends should be considered a regression.  Existing functionality was lost.

**Comment by thriveth** [comment]
I agree that this is an important feature. Unfortunately I do not have the coding skill to contribute it myself.

**Comment by 01baftb** [comment]
+1 for this feature request.
