### ISSUE TITLE
[Windows] Installing from conda does not enable in notebook

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/jupyter-matplotlib#46]
`%matplotlib ipympl` does not work for me in Windows when installing ipympl from conda. Could be the case for other OS as well.

The following code is an example that works in lab but not in notebook after following the readme instructions:

```python
%matplotlib ipympl
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```

I can enable plotting by calling `jupyter nbextension enable --py --sys-prefix ipympl`, as per the **pip** instructions. If `conda install ipympl widgetsnbextension` is supposed to do that under the hood, then it is not working. If it does not include that, we should fix that or add the above command to the installation instructions.

It would be great if someone else could reproduce this, in case I'm wrong.

**Comment by SylvainCorlay** [comment]
@thomasaarholt I have opened a PR in the conda-forge feedstock, which should resolve this. It will take a few hours before it is reflected on the conda channel because of the build queue.

Thanks for reporting!

**Comment by thomasaarholt** [comment]
That's great! Thanks Sylvain!
