### ISSUE TITLE
DeprecationWarning from traitlets

### ISSUE THREAD

**Issue by NathanDunfield** [matplotlib/jupyter-matplotlib#51]
With DeprecationWarnings on, I get the following warning message with ipympl 0.1.1 and traitlets 4.3.2:
```
/sage/local/lib/python2.7/site-packages/ipympl/backend_nbagg.py:125: 
DeprecationWarning: metadata {'sync': True} was set from the constructor. 
With traitlets 4.1, metadata should be set using the .tag() method, e.g., 
Int().tag(key1='value1', key2='value2')
  _model_module = Unicode('jupyter-matplotlib', sync=True)
```
So line 125 (and the subsequent similar code) should be updated to 
```
  _model_module = Unicode('jupyter-matplotlib').tag(sync=True)
```
The current `ipympl` requires `ipywidgets>=7.0` which in turn requires `traitlets>=4.3.1`, so there is no need to support `traitlets < 4.1`.

**Comment by SylvainCorlay** [comment]
Thanks @NathanDunfield! Good catch.

Feel free to open a PR. I would be happy to merge.

**Comment by NathanDunfield** [comment]
@SylvainCorlay PR created!

**Comment by SylvainCorlay** [comment]
Thanks!
