### ISSUE TITLE
Interactivity very slow

### ISSUE THREAD

**Issue by tammojan** [matplotlib/jupyter-matplotlib#55]
When e.g. panning a graph in a matplotlib widget, it takes seconds for the graph to respond to this. Is this a known issue?

I'm using ipympl-0.2.0-py2.py3.

**Comment by SylvainCorlay** [comment]
Yes. Matplotlib does all the rendering in the backend and ipympl streams diffs of pngs to the frontend.

If there is network latency, it can be long (probably not seconds though).

If you are interested in more interactivity, you can look at other libraries that perform the rendering in the front end. There are many (bqplot, bokeh, plotly, altair).

There are some optimizations that are coming up in ipympl though to improve the situation but it will never be as snappy as a browser-based solution.
