### ISSUE TITLE
Python 3.7 support on conda-forge

### ISSUE THREAD

**Issue by thomasaarholt** [matplotlib/jupyter-matplotlib#58]
Currently trying to install python 3.7 by cloning a my current python 3.6 conda environment, and installing python 3.7 into it. Conda correctly updates most packages without issue, but ipympl stands out as downgrading to a much previous version number.

```python
(py36) >>> conda create --name py37 --clone py36
(py36) >>> source activate py37
(py37) >>> conda install -c anaconda python=3.7
# Most packages update to their 3.7 versions fine, but:
The following packages will be DOWNGRADED:
    ipympl:                        0.2.1-py36_0            conda-forge --> 0.0.8-py_0             conda-forge
```
Can we build a conda package for py37?

**Comment by dopplershift** [comment]
Matplotlib itself does not control the Anaconda or conda-forge packages. For Anaconda, you need to raise this on their issue tracker. For conda-forge, they are currently working on a massive rebuild of all packages, so a Python 3.7 package will be rebuilt once all of the dependencies are available on Python 3.7. It looks like there's already an open issue you can comment on: conda-forge/ipympl-feedstock#19.

**Comment by greglucas** [comment]
The ipympl feedstock should be updated now. Installing this in a new python 3.7 conda environment worked for me.

**Comment by thomasaarholt** [comment]
Glad to hear it.
