### ISSUE TITLE
How to resize the plot when using "%matplotlib widget"

### ISSUE THREAD

**Issue by alucardkoten** [matplotlib/jupyter-matplotlib#74]
When I used the "%matplotlib notebook," there is a small triangle in the right bottom corner of the plot that your can drag to resize. But it seems that this feature disappeared in the "%matplotlib widget" mode. I wonder how can I resize the plot by dragging.

**Comment by jakirkham** [comment]
Looks like issue ( https://github.com/matplotlib/jupyter-matplotlib/issues/44 ) is asking for the same feature. Should one of these be closed?

**Comment by 01baftb** [comment]
+1 for this feature request.

**Comment by martinRenou** [comment]
Closing as duplicate https://github.com/matplotlib/jupyter-matplotlib/issues/44, thanks for reporting! It would be indeed a nice feature
