### ISSUE TITLE
Interactive labels (rendered title, pan/zoom, x=, y=, etc) hard to read in dark theme

### ISSUE THREAD

**Issue by davidlow** [matplotlib/jupyter-matplotlib#77]
Hello,

When plotting in a jupyterlab notebook with jupyter-matplotlib interactive mode with the default jupyterlab dark theme, the figure title and labels for the interactive mode are very hard to read.  By labels, I mean "pan/zoom" or "zoom to rectangle" that you get when you pan over the interactive buttons, and the x,y positions when you hover over a portion of the plot.

I see that this issue has been replicated before in [#25](https://github.com/matplotlib/jupyter-matplotlib/issues/25) but to me it looks like the solution there was to change the matplotlib style sheet to force different colored figure titles.  This did not work for the labels on the interactive plot for me.  

Here is some code to replicate the problem:
```
import numpy as np
import matplotlib.pyplot as plt
plt.ion()
plt.style.use(['dark_background'])
```

```
%matplotlib ipympl
```

```
x = np.linspace(-10,10,1000)
y = np.sin(x)*np.cos(10*x)
```

```
fig,ax = plt.subplots()
ax.plot(x,y)
```

and an image of my problem.

![image](https://user-images.githubusercontent.com/13804016/51781697-46a82d00-2114-11e9-9f8c-2fc9a0b8f2a2.png)

If you look very closely at the center of the top of the figure, you can see "figure 1" and on the bottom right, you can see "zoom rec x=-.02..., y=.08...".

As I noted before, this was also found in #25 [here](https://github.com/matplotlib/jupyter-matplotlib/issues/25#issuecomment-340405846) by @blink1073.

**Comment by davidlow** [comment]
I can highlight the "figure 1" to make it easier to see.

![image](https://user-images.githubusercontent.com/13804016/51781827-5de81a00-2116-11e9-82e0-9164ed53d311.png)

**Comment by martinRenou** [comment]
This is fixed on master
