### ISSUE TITLE
plots capture scrolling

### ISSUE THREAD

**Issue by ces42** [matplotlib/jupyter-matplotlib#81]
scrolling while the mouse is over a plot doesn't scroll in the document (the notebook activity indicator seems to suggest that "scroll events" are processed by the widget). However nothing happens (no zooming into the plot etc.). 
Not being able to scroll while the mouse is on some parts of the notebook is very annoying for me.

Is it possible to implement an option which would disable this?

**Comment by tacaswell** [comment]
The scroll events are being captured and passed back to the backend, however there is no default action bound to the scroll events.

All of the other interactive backends support scroll events, I am worried about ipympl diverging from the standard behavior and now that we have jlab and do not need to have the figures in-line (not `inline`) in notebooks I suspect that this will become less of an issue.

**Comment by SylvainCorlay** [comment]
@tacaswell Thanks for looking into this.

What we have been doing is try to reduce the amount of code and make it more idiomatic to what we usually do in the Jupyter world. I am fine with re-adding the scroll events later on.
